name: Auto Tweet Using AI

on:
  schedule:
    - cron: "0 10 * * *"  # Runs every day at 10 AM
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@master

    # - name: Download counter artifact
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: counter
    #     run-id: ${{ github.event.workflow_run.id }}
    #     path: ./  # Ensure the counter.txt is placed in the root directory

    - name: Install Dependencies
      run: npm install

    - name: Run Twitter bot
      run: npm start

    - name: Upload counter artifact
      uses: actions/upload-artifact@v4
      with:
        name: counter
        path: counter.txt
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
